
version: 1

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
    
sphinx:
  version: 4.4.0

docs:
  master:
    main: true
    root: README

html:
  extra_files:
    - metadata.json
    - Dockerfile
    - ToAnalize/*
    - Results/*
    - iaos.py
    - IAOS.py
